# Generated by Django 3.2.2 on 2021-05-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('class_subject', models.CharField(max_length=200)),
                ('class_code', models.CharField(max_length=8)),
                ('class_admin', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_desc', models.CharField(max_length=500)),
                ('qn_marks', models.IntegerField()),
                ('qn_date', models.DateTimeField(auto_now_add=True)),
                ('qn_deadline', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_classway.class')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_desc', models.CharField(max_length=10000)),
                ('ans_date', models.DateTimeField(auto_now_add=True)),
                ('ans_marks', models.IntegerField()),
                ('qn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_classway.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
