# Generated by Django 3.2.2 on 2021-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_desc',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_desc',
            field=models.TextField(max_length=500),
        ),
    ]
