# Generated by Django 3.2.2 on 2021-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0003_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
    ]
