# Generated by Django 3.2.2 on 2021-05-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0004_remove_class_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user_id',
        ),
    ]
