# Generated by Django 3.2.2 on 2021-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0006_auto_20210518_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='classx',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='userx',
            new_name='user_id',
        ),
    ]
