# Generated by Django 3.2.2 on 2021-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0007_auto_20210518_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_admin',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_subject',
            field=models.CharField(max_length=30),
        ),
    ]
