# Generated by Django 3.2.2 on 2021-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_classway', '0008_auto_20210519_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_marks',
            field=models.IntegerField(null=True),
        ),
    ]
